// <auto-generated />
using System;
using GrapheneTrace_GP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GrapheneTrace_GP.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251208224302_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GrapheneTrace_GP.Areas.Admin.Models.Clinicians", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClinicianAge")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClinicianFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClinicianId")
                        .HasColumnType("int");

                    b.Property<string>("ClinicianLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClinicianSpeciality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clinicians");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "1 Main Street",
                            City = "London",
                            ClinicianAge = "40",
                            ClinicianFirstName = "John",
                            ClinicianId = 852693,
                            ClinicianLastName = "Michael",
                            ClinicianSpeciality = "Cardiologist",
                            DateOfBirth = new DateTime(1984, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john.michael@example.com",
                            Gender = "Male",
                            Phone = "07111111111",
                            PostCode = "A1 1AA",
                            Status = "Active",
                            Title = "Dr."
                        },
                        new
                        {
                            Id = 2,
                            Address = "2 Main Street",
                            City = "London",
                            ClinicianAge = "32",
                            ClinicianFirstName = "Sarah",
                            ClinicianId = 698235,
                            ClinicianLastName = "Peterson",
                            ClinicianSpeciality = "Neurology",
                            DateOfBirth = new DateTime(1992, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sarah.peterson@hospital.com",
                            Gender = "Female",
                            Phone = "07222222222",
                            PostCode = "A2 2BB",
                            Status = "Active",
                            Title = "Dr."
                        },
                        new
                        {
                            Id = 3,
                            Address = "3 Main Street",
                            City = "London",
                            ClinicianAge = "30",
                            ClinicianFirstName = "Emily",
                            ClinicianId = 456973,
                            ClinicianLastName = "Johnson",
                            ClinicianSpeciality = "Pediatrics",
                            DateOfBirth = new DateTime(1994, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emily.johnson@hospital.com",
                            Gender = "Female",
                            Phone = "07333333333",
                            PostCode = "A3 3CC",
                            Status = "Active",
                            Title = "Dr."
                        },
                        new
                        {
                            Id = 4,
                            Address = "4 Main Street",
                            City = "London",
                            ClinicianAge = "29",
                            ClinicianFirstName = "David",
                            ClinicianId = 325698,
                            ClinicianLastName = "Anderson",
                            ClinicianSpeciality = "Neurologist",
                            DateOfBirth = new DateTime(1995, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "david.anderson@hospital.com",
                            Gender = "Male",
                            Phone = "07444444444",
                            PostCode = "A4 4DD",
                            Status = "Active",
                            Title = "Dr."
                        },
                        new
                        {
                            Id = 5,
                            Address = "5 Main Street",
                            City = "London",
                            ClinicianAge = "49",
                            ClinicianFirstName = "Emmanuel",
                            ClinicianId = 258963,
                            ClinicianLastName = "State",
                            ClinicianSpeciality = "Surgeon",
                            DateOfBirth = new DateTime(1975, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emmanuel.state@hospital.com",
                            Gender = "Male",
                            Phone = "07555555555",
                            PostCode = "A5 5EE",
                            Status = "Active",
                            Title = "Dr."
                        },
                        new
                        {
                            Id = 6,
                            Address = "6 Main Street",
                            City = "London",
                            ClinicianAge = "42",
                            ClinicianFirstName = "Mike",
                            ClinicianId = 258694,
                            ClinicianLastName = "Stephen",
                            ClinicianSpeciality = "Radiologist",
                            DateOfBirth = new DateTime(1982, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mike.stephen@hospital.com",
                            Gender = "Male",
                            Phone = "07666666666",
                            PostCode = "A6 6FF",
                            Status = "Active",
                            Title = "Dr."
                        },
                        new
                        {
                            Id = 7,
                            Address = "7 Main Street",
                            City = "London",
                            ClinicianAge = "38",
                            ClinicianFirstName = "Noah",
                            ClinicianId = 784561,
                            ClinicianLastName = "Hyper",
                            ClinicianSpeciality = "Psychiatrist",
                            DateOfBirth = new DateTime(1986, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "noah.hyper@hospital.com",
                            Gender = "Male",
                            Phone = "07777777777",
                            PostCode = "A7 7GG",
                            Status = "Active",
                            Title = "Dr."
                        },
                        new
                        {
                            Id = 8,
                            Address = "8 Main Street",
                            City = "London",
                            ClinicianAge = "38",
                            ClinicianFirstName = "Helen",
                            ClinicianId = 125489,
                            ClinicianLastName = "Cooke",
                            ClinicianSpeciality = "Gynaecologist",
                            DateOfBirth = new DateTime(1986, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "helen.cooke@hospital.com",
                            Gender = "Female",
                            Phone = "07888888888",
                            PostCode = "A8 8HH",
                            Status = "Active",
                            Title = "Dr."
                        },
                        new
                        {
                            Id = 9,
                            Address = "9 Main Street",
                            City = "London",
                            ClinicianAge = "42",
                            ClinicianFirstName = "Rose",
                            ClinicianId = 508342,
                            ClinicianLastName = "Night",
                            ClinicianSpeciality = "Surgeon",
                            DateOfBirth = new DateTime(1982, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "rose.night@hospital.com",
                            Gender = "Female",
                            Phone = "07999999999",
                            PostCode = "A9 9JJ",
                            Status = "Active",
                            Title = "Dr."
                        },
                        new
                        {
                            Id = 10,
                            Address = "10 Main Street",
                            City = "London",
                            ClinicianAge = "54",
                            ClinicianFirstName = "Jake",
                            ClinicianId = 159753,
                            ClinicianLastName = "Watson",
                            ClinicianSpeciality = "Orthopaedic",
                            DateOfBirth = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jake.watson@hospital.com",
                            Gender = "Male",
                            Phone = "07010101010",
                            PostCode = "B1 1AA",
                            Status = "Active",
                            Title = "Dr."
                        },
                        new
                        {
                            Id = 11,
                            Address = "11 Main Street",
                            City = "London",
                            ClinicianAge = "34",
                            ClinicianFirstName = "Emma",
                            ClinicianId = 753561,
                            ClinicianLastName = "Richard",
                            ClinicianSpeciality = "Dermatologist",
                            DateOfBirth = new DateTime(1990, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emma.richard@hospital.com",
                            Gender = "Female",
                            Phone = "07020202020",
                            PostCode = "B2 2BB",
                            Status = "Active",
                            Title = "Dr."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
