// <auto-generated />
using System;
using GrapheneTrace_GP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GrapheneTrace_GP.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251210170330_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GrapheneTrace_GP.Areas.Admin.Models.Clinicians", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClinicianAge")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClinicianFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClinicianId")
                        .HasColumnType("int");

                    b.Property<string>("ClinicianLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClinicianSpeciality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clinicians");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "1 Main Street",
                            City = "London",
                            ClinicianAge = "40",
                            ClinicianFirstName = "John",
                            ClinicianId = 852693,
                            ClinicianLastName = "Michael",
                            ClinicianSpeciality = "Cardiologist",
                            DateOfBirth = new DateTime(1984, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john.michael@example.com",
                            Gender = "Male",
                            Phone = "07111111111",
                            PostCode = "A1 1AA",
                            Status = "Active",
                            Title = "Dr."
                        },
                        new
                        {
                            Id = 2,
                            Address = "2 Main Street",
                            City = "London",
                            ClinicianAge = "32",
                            ClinicianFirstName = "Sarah",
                            ClinicianId = 698235,
                            ClinicianLastName = "Peterson",
                            ClinicianSpeciality = "Neurology",
                            DateOfBirth = new DateTime(1992, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sarah.peterson@hospital.com",
                            Gender = "Female",
                            Phone = "07222222222",
                            PostCode = "A2 2BB",
                            Status = "Active",
                            Title = "Dr."
                        },
                        new
                        {
                            Id = 3,
                            Address = "3 Main Street",
                            City = "London",
                            ClinicianAge = "30",
                            ClinicianFirstName = "Emily",
                            ClinicianId = 456973,
                            ClinicianLastName = "Johnson",
                            ClinicianSpeciality = "Pediatrics",
                            DateOfBirth = new DateTime(1994, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emily.johnson@hospital.com",
                            Gender = "Female",
                            Phone = "07333333333",
                            PostCode = "A3 3CC",
                            Status = "Active",
                            Title = "Dr."
                        },
                        new
                        {
                            Id = 4,
                            Address = "4 Main Street",
                            City = "London",
                            ClinicianAge = "29",
                            ClinicianFirstName = "David",
                            ClinicianId = 325698,
                            ClinicianLastName = "Anderson",
                            ClinicianSpeciality = "Neurologist",
                            DateOfBirth = new DateTime(1995, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "david.anderson@hospital.com",
                            Gender = "Male",
                            Phone = "07444444444",
                            PostCode = "A4 4DD",
                            Status = "Active",
                            Title = "Dr."
                        },
                        new
                        {
                            Id = 5,
                            Address = "5 Main Street",
                            City = "London",
                            ClinicianAge = "49",
                            ClinicianFirstName = "Emmanuel",
                            ClinicianId = 258963,
                            ClinicianLastName = "State",
                            ClinicianSpeciality = "Surgeon",
                            DateOfBirth = new DateTime(1975, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emmanuel.state@hospital.com",
                            Gender = "Male",
                            Phone = "07555555555",
                            PostCode = "A5 5EE",
                            Status = "Active",
                            Title = "Dr."
                        },
                        new
                        {
                            Id = 6,
                            Address = "6 Main Street",
                            City = "London",
                            ClinicianAge = "42",
                            ClinicianFirstName = "Mike",
                            ClinicianId = 258694,
                            ClinicianLastName = "Stephen",
                            ClinicianSpeciality = "Radiologist",
                            DateOfBirth = new DateTime(1982, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mike.stephen@hospital.com",
                            Gender = "Male",
                            Phone = "07666666666",
                            PostCode = "A6 6FF",
                            Status = "Active",
                            Title = "Dr."
                        },
                        new
                        {
                            Id = 7,
                            Address = "7 Main Street",
                            City = "London",
                            ClinicianAge = "38",
                            ClinicianFirstName = "Noah",
                            ClinicianId = 784561,
                            ClinicianLastName = "Hyper",
                            ClinicianSpeciality = "Psychiatrist",
                            DateOfBirth = new DateTime(1986, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "noah.hyper@hospital.com",
                            Gender = "Male",
                            Phone = "07777777777",
                            PostCode = "A7 7GG",
                            Status = "Active",
                            Title = "Dr."
                        },
                        new
                        {
                            Id = 8,
                            Address = "8 Main Street",
                            City = "London",
                            ClinicianAge = "38",
                            ClinicianFirstName = "Helen",
                            ClinicianId = 125489,
                            ClinicianLastName = "Cooke",
                            ClinicianSpeciality = "Gynaecologist",
                            DateOfBirth = new DateTime(1986, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "helen.cooke@hospital.com",
                            Gender = "Female",
                            Phone = "07888888888",
                            PostCode = "A8 8HH",
                            Status = "Active",
                            Title = "Dr."
                        },
                        new
                        {
                            Id = 9,
                            Address = "9 Main Street",
                            City = "London",
                            ClinicianAge = "42",
                            ClinicianFirstName = "Rose",
                            ClinicianId = 508342,
                            ClinicianLastName = "Night",
                            ClinicianSpeciality = "Surgeon",
                            DateOfBirth = new DateTime(1982, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "rose.night@hospital.com",
                            Gender = "Female",
                            Phone = "07999999999",
                            PostCode = "A9 9JJ",
                            Status = "Active",
                            Title = "Dr."
                        },
                        new
                        {
                            Id = 10,
                            Address = "10 Main Street",
                            City = "London",
                            ClinicianAge = "54",
                            ClinicianFirstName = "Jake",
                            ClinicianId = 159753,
                            ClinicianLastName = "Watson",
                            ClinicianSpeciality = "Orthopaedic",
                            DateOfBirth = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jake.watson@hospital.com",
                            Gender = "Male",
                            Phone = "07010101010",
                            PostCode = "B1 1AA",
                            Status = "Active",
                            Title = "Dr."
                        },
                        new
                        {
                            Id = 11,
                            Address = "11 Main Street",
                            City = "London",
                            ClinicianAge = "34",
                            ClinicianFirstName = "Emma",
                            ClinicianId = 753561,
                            ClinicianLastName = "Richard",
                            ClinicianSpeciality = "Dermatologist",
                            DateOfBirth = new DateTime(1990, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emma.richard@hospital.com",
                            Gender = "Female",
                            Phone = "07020202020",
                            PostCode = "B2 2BB",
                            Status = "Active",
                            Title = "Dr."
                        });
                });

            modelBuilder.Entity("GrapheneTrace_GP.Areas.Admin.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientAge")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PatientId");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            PatientId = 2693,
                            Address = "10 Downing Street",
                            City = "London",
                            DateOfBirth = new DateTime(1984, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sophie.night@gmail.com",
                            FirstName = "Sophie",
                            Gender = "Female",
                            Id = 0,
                            LastName = "Night",
                            PatientAge = "40",
                            Phone = "07012345678",
                            PostCode = "SW1A 2AA",
                            Status = "Active",
                            Title = "Mrs."
                        },
                        new
                        {
                            PatientId = 5987,
                            Address = "20 Baker Street",
                            City = "London",
                            DateOfBirth = new DateTime(1992, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "janee.harrison@gmail.com",
                            FirstName = "Janee",
                            Gender = "Female",
                            Id = 0,
                            LastName = "Harrison",
                            PatientAge = "32",
                            Phone = "07087654321",
                            PostCode = "NW1 6XE",
                            Status = "Active",
                            Title = "Ms."
                        },
                        new
                        {
                            PatientId = 8963,
                            Address = "30 Oxford Street",
                            City = "London",
                            DateOfBirth = new DateTime(1995, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mike.jackson@gmail.com",
                            FirstName = "Mike",
                            Gender = "Male",
                            Id = 0,
                            LastName = "Jackson",
                            PatientAge = "29",
                            Phone = "07011223344",
                            PostCode = "W1D 1BS",
                            Status = "Alert",
                            Title = "Mr"
                        },
                        new
                        {
                            PatientId = 1257,
                            Address = "40 King Street",
                            City = "London",
                            DateOfBirth = new DateTime(1978, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "peter.benjamin@gmail.com",
                            FirstName = "Peter",
                            Gender = "Male",
                            Id = 0,
                            LastName = "Benjamin",
                            PatientAge = "49",
                            Phone = "07098765432",
                            PostCode = "W1F 0UT",
                            Status = "Active",
                            Title = "Mr."
                        },
                        new
                        {
                            PatientId = 9862,
                            Address = "50 Queen Street",
                            City = "London",
                            DateOfBirth = new DateTime(1988, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Hannah.green@gmail.com",
                            FirstName = "Hannah",
                            Gender = "Female",
                            Id = 0,
                            LastName = "Green",
                            PatientAge = "42",
                            Phone = "07012345678",
                            PostCode = "W1A 1AA",
                            Status = "Active",
                            Title = "Mrs."
                        },
                        new
                        {
                            PatientId = 3654,
                            Address = "60 King Street",
                            City = "London",
                            DateOfBirth = new DateTime(1986, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "andy.bryan@gmail.com",
                            FirstName = "Andy",
                            Gender = "Male",
                            Id = 0,
                            LastName = "Bryan",
                            PatientAge = "38",
                            Phone = "07012345678",
                            PostCode = "W1F 0UT",
                            Status = "Not Active",
                            Title = "Mr"
                        },
                        new
                        {
                            PatientId = 4527,
                            Address = "70 King Street",
                            City = "London",
                            DateOfBirth = new DateTime(1986, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "alex.white@gmail.com",
                            FirstName = "Alex",
                            Gender = "Male",
                            Id = 0,
                            LastName = "White",
                            PatientAge = "38",
                            Phone = "07012345678",
                            PostCode = "W1F 0UT",
                            Status = "Active",
                            Title = "Mr"
                        },
                        new
                        {
                            PatientId = 6723,
                            Address = "80 Queen Street",
                            City = "London",
                            DateOfBirth = new DateTime(1994, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "clara.ashley@gmail.com",
                            FirstName = "Clara",
                            Gender = "Female",
                            Id = 0,
                            LastName = "Ashley",
                            PatientAge = "30",
                            Phone = "07012345678",
                            PostCode = "W1A 1AA",
                            Status = "Not Active",
                            Title = "Mrs."
                        },
                        new
                        {
                            PatientId = 7894,
                            Address = "90 Queen Street",
                            City = "London",
                            DateOfBirth = new DateTime(1990, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "diana.prince@gmail.com",
                            FirstName = "Diana",
                            Gender = "Female",
                            Id = 0,
                            LastName = "Prince",
                            PatientAge = "34",
                            Phone = "07012345678",
                            PostCode = "W1A 1AA",
                            Status = "Not Active",
                            Title = "Ms."
                        },
                        new
                        {
                            PatientId = 3456,
                            Address = "100 Gotham Street",
                            City = "Gotham",
                            DateOfBirth = new DateTime(1978, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "richard.watson@gmail.com",
                            FirstName = "Richard",
                            Gender = "Male",
                            Id = 0,
                            LastName = "Watson",
                            PatientAge = "45",
                            Phone = "07012345678",
                            PostCode = "G1TH 0TH",
                            Status = "Active",
                            Title = "Mr"
                        },
                        new
                        {
                            PatientId = 9123,
                            Address = "110 Gotham Street",
                            City = "Gotham",
                            DateOfBirth = new DateTime(1995, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "james.brown@gmail.com",
                            FirstName = "James",
                            Gender = "Female",
                            Id = 0,
                            LastName = "Brown",
                            PatientAge = "28",
                            Phone = "07012345678",
                            PostCode = "G1TH 0TH",
                            Status = "Not Active",
                            Title = "Mr."
                        },
                        new
                        {
                            PatientId = 4569,
                            Address = "20 Avenue Glass Rd",
                            City = "Bristol",
                            DateOfBirth = new DateTime(1986, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Olivia12.Patrick@gmail.com",
                            FirstName = "Olivia",
                            Gender = "Female",
                            Id = 0,
                            LastName = "Patrick",
                            PatientAge = "39",
                            Phone = "07452136925",
                            PostCode = "B17G BYR",
                            Status = "Active",
                            Title = "Ms"
                        },
                        new
                        {
                            PatientId = 7891,
                            Address = "30 River Side",
                            City = "Manchester",
                            DateOfBirth = new DateTime(1988, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "liam.smith@gmail.com",
                            FirstName = "Liam",
                            Gender = "Male",
                            Id = 0,
                            LastName = "Smith",
                            PatientAge = "35",
                            Phone = "07345678912",
                            PostCode = "M1 2AB",
                            Status = "Active",
                            Title = "Mr."
                        },
                        new
                        {
                            PatientId = 2345,
                            Address = "40 River Side",
                            City = "Manchester",
                            DateOfBirth = new DateTime(1982, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ava.johnson@gmail.com",
                            FirstName = "Ava",
                            Gender = "Female",
                            Id = 0,
                            LastName = "Johnson",
                            PatientAge = "41",
                            Phone = "07345678912",
                            PostCode = "M1 2AB",
                            Status = "Not Active",
                            Title = "Mrs."
                        },
                        new
                        {
                            PatientId = 6789,
                            Address = "50 River Side",
                            City = "Manchester",
                            DateOfBirth = new DateTime(1994, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "isabella.williams@gmail.com",
                            FirstName = "Isabella",
                            Gender = "Female",
                            Id = 0,
                            LastName = "Williams",
                            PatientAge = "29",
                            Phone = "07412345678",
                            PostCode = "M1 2AB",
                            Status = "Active",
                            Title = "Ms."
                        },
                        new
                        {
                            PatientId = 3457,
                            Address = "60 River Side",
                            City = "Manchester",
                            DateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "noah.brown@gmail.com",
                            FirstName = "Noah",
                            Gender = "Male",
                            Id = 0,
                            LastName = "Brown",
                            PatientAge = "33",
                            Phone = "07512345678",
                            PostCode = "M1 2AB",
                            Status = "Active",
                            Title = "Mr."
                        });
                });

            modelBuilder.Entity("GrapheneTrace_GP.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("NextAppointment")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("TreatmentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AppointmentId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            AppointmentId = 1,
                            AppointmentDate = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comments = "Routine visit",
                            IsCompleted = false,
                            NextAppointment = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 2693,
                            TreatmentType = "General Checkup"
                        },
                        new
                        {
                            AppointmentId = 2,
                            AppointmentDate = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comments = "Normal results",
                            IsCompleted = true,
                            NextAppointment = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 2693,
                            TreatmentType = "Blood Test"
                        },
                        new
                        {
                            AppointmentId = 3,
                            AppointmentDate = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comments = "Progressing well",
                            IsCompleted = false,
                            NextAppointment = new DateTime(2024, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 2693,
                            TreatmentType = "Physical Therapy"
                        },
                        new
                        {
                            AppointmentId = 4,
                            AppointmentDate = new DateTime(2024, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comments = "Stable condition",
                            IsCompleted = true,
                            PatientId = 2693,
                            TreatmentType = "Follow-up"
                        },
                        new
                        {
                            AppointmentId = 5,
                            AppointmentDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comments = "Good oral hygiene",
                            IsCompleted = true,
                            NextAppointment = new DateTime(2024, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 5987,
                            TreatmentType = "Dental Cleaning"
                        },
                        new
                        {
                            AppointmentId = 6,
                            AppointmentDate = new DateTime(2024, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comments = "No issues detected",
                            IsCompleted = true,
                            PatientId = 5987,
                            TreatmentType = "X-Ray"
                        },
                        new
                        {
                            AppointmentId = 7,
                            AppointmentDate = new DateTime(2024, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comments = "Healthy",
                            IsCompleted = false,
                            NextAppointment = new DateTime(2024, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 5987,
                            TreatmentType = "General Checkup"
                        },
                        new
                        {
                            AppointmentId = 8,
                            AppointmentDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comments = "Prescribed glasses",
                            IsCompleted = true,
                            PatientId = 5987,
                            TreatmentType = "Eye Examination"
                        },
                        new
                        {
                            AppointmentId = 9,
                            AppointmentDate = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comments = "Minor spinal issue",
                            IsCompleted = false,
                            NextAppointment = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 8963,
                            TreatmentType = "MRI Scan"
                        },
                        new
                        {
                            AppointmentId = 10,
                            AppointmentDate = new DateTime(2024, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comments = "Back pain improving",
                            IsCompleted = true,
                            PatientId = 8963,
                            TreatmentType = "Physiotherapy"
                        },
                        new
                        {
                            AppointmentId = 11,
                            AppointmentDate = new DateTime(2024, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comments = "Condition stable",
                            IsCompleted = true,
                            PatientId = 8963,
                            TreatmentType = "Follow-up"
                        },
                        new
                        {
                            AppointmentId = 12,
                            AppointmentDate = new DateTime(2024, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comments = "No serious issues",
                            IsCompleted = true,
                            PatientId = 8963,
                            TreatmentType = "Neurology Review"
                        },
                        new
                        {
                            AppointmentId = 13,
                            AppointmentDate = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comments = "Healthy",
                            IsCompleted = true,
                            NextAppointment = new DateTime(2024, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 1257,
                            TreatmentType = "General Checkup"
                        },
                        new
                        {
                            AppointmentId = 14,
                            AppointmentDate = new DateTime(2024, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comments = "Low iron",
                            IsCompleted = false,
                            NextAppointment = new DateTime(2024, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 1257,
                            TreatmentType = "Blood Work"
                        },
                        new
                        {
                            AppointmentId = 15,
                            AppointmentDate = new DateTime(2024, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comments = "Diet plan issued",
                            IsCompleted = true,
                            PatientId = 1257,
                            TreatmentType = "Nutrition Consultation"
                        },
                        new
                        {
                            AppointmentId = 16,
                            AppointmentDate = new DateTime(2024, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comments = "Updated records",
                            IsCompleted = true,
                            PatientId = 1257,
                            TreatmentType = "Vaccination"
                        },
                        new
                        {
                            AppointmentId = 17,
                            AppointmentDate = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comments = "Healthy",
                            IsCompleted = true,
                            NextAppointment = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 9862,
                            TreatmentType = "General Checkup"
                        },
                        new
                        {
                            AppointmentId = 18,
                            AppointmentDate = new DateTime(2024, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comments = "No issues",
                            IsCompleted = true,
                            PatientId = 9862,
                            TreatmentType = "Skin Screening"
                        },
                        new
                        {
                            AppointmentId = 19,
                            AppointmentDate = new DateTime(2024, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comments = "Vision normal",
                            IsCompleted = true,
                            PatientId = 9862,
                            TreatmentType = "Eye Test"
                        },
                        new
                        {
                            AppointmentId = 20,
                            AppointmentDate = new DateTime(2024, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comments = "All good",
                            IsCompleted = true,
                            PatientId = 9862,
                            TreatmentType = "Follow-up"
                        },
                        new
                        {
                            AppointmentId = 21,
                            AppointmentDate = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comments = "Inactive lifestyle noted",
                            IsCompleted = false,
                            NextAppointment = new DateTime(2024, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 3654,
                            TreatmentType = "General Checkup"
                        },
                        new
                        {
                            AppointmentId = 22,
                            AppointmentDate = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comments = "Borderline results",
                            IsCompleted = true,
                            PatientId = 3654,
                            TreatmentType = "Cardio Stress Test"
                        },
                        new
                        {
                            AppointmentId = 23,
                            AppointmentDate = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comments = "Plan provided",
                            IsCompleted = true,
                            PatientId = 3654,
                            TreatmentType = "Diet Consultation"
                        },
                        new
                        {
                            AppointmentId = 24,
                            AppointmentDate = new DateTime(2024, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comments = "Improving",
                            IsCompleted = true,
                            PatientId = 3654,
                            TreatmentType = "Follow-up"
                        },
                        new
                        {
                            AppointmentId = 25,
                            AppointmentDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comments = "Mild allergies found",
                            IsCompleted = true,
                            PatientId = 4527,
                            TreatmentType = "Allergy Test"
                        },
                        new
                        {
                            AppointmentId = 26,
                            AppointmentDate = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comments = "Good health",
                            IsCompleted = true,
                            PatientId = 4527,
                            TreatmentType = "General Checkup"
                        },
                        new
                        {
                            AppointmentId = 27,
                            AppointmentDate = new DateTime(2024, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comments = "Results normal",
                            IsCompleted = true,
                            PatientId = 4527,
                            TreatmentType = "Blood Test"
                        },
                        new
                        {
                            AppointmentId = 28,
                            AppointmentDate = new DateTime(2024, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comments = "No issues",
                            IsCompleted = true,
                            PatientId = 4527,
                            TreatmentType = "X-Ray"
                        },
                        new
                        {
                            AppointmentId = 29,
                            AppointmentDate = new DateTime(2024, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comments = "Inactive status noted",
                            IsCompleted = true,
                            PatientId = 6723,
                            TreatmentType = "General Checkup"
                        },
                        new
                        {
                            AppointmentId = 30,
                            AppointmentDate = new DateTime(2024, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comments = "Good teeth",
                            IsCompleted = true,
                            PatientId = 6723,
                            TreatmentType = "Dental Cleaning"
                        },
                        new
                        {
                            AppointmentId = 31,
                            AppointmentDate = new DateTime(2024, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comments = "Reading glasses advised",
                            IsCompleted = true,
                            PatientId = 6723,
                            TreatmentType = "Eye Examination"
                        },
                        new
                        {
                            AppointmentId = 32,
                            AppointmentDate = new DateTime(2024, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comments = "Clear",
                            IsCompleted = true,
                            PatientId = 6723,
                            TreatmentType = "Skin Screening"
                        },
                        new
                        {
                            AppointmentId = 33,
                            AppointmentDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comments = "Very healthy",
                            IsCompleted = true,
                            NextAppointment = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 7894,
                            TreatmentType = "General Checkup"
                        },
                        new
                        {
                            AppointmentId = 34,
                            AppointmentDate = new DateTime(2024, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comments = "Cleared for activity",
                            IsCompleted = true,
                            PatientId = 7894,
                            TreatmentType = "Sports Physical"
                        },
                        new
                        {
                            AppointmentId = 35,
                            AppointmentDate = new DateTime(2024, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comments = "Improved posture",
                            IsCompleted = true,
                            PatientId = 7894,
                            TreatmentType = "Chiropractic Adjustment"
                        },
                        new
                        {
                            AppointmentId = 36,
                            AppointmentDate = new DateTime(2024, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comments = "Excellent condition",
                            IsCompleted = true,
                            PatientId = 7894,
                            TreatmentType = "Follow-up"
                        });
                });

            modelBuilder.Entity("GrapheneTrace_GP.Models.Appointment", b =>
                {
                    b.HasOne("GrapheneTrace_GP.Areas.Admin.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });
#pragma warning restore 612, 618
        }
    }
}
