// <auto-generated />
using System;
using GrapheneTrace_GP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GrapheneTrace_GP.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251214120132_RevertFixClinicianNullableFields")]
    partial class RevertFixClinicianNullableFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("NextAppointment")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("TreatmentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AppointmentId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("GrapheneTrace_GP.Areas.Admin.Models.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlertCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelatedId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Alerts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlertCode = "ALT-01",
                            CreatedAt = new DateTime(2025, 2, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "System software update available - pending installation approval",
                            Priority = "Medium",
                            Status = "Read",
                            Type = "System"
                        },
                        new
                        {
                            Id = 2,
                            AlertCode = "ALT-02",
                            CreatedAt = new DateTime(2025, 2, 1, 11, 20, 0, 0, DateTimeKind.Unspecified),
                            Message = "Profile verification pending for Dr Anderson",
                            Priority = "High",
                            RelatedId = "325698",
                            Status = "Unread",
                            Type = "System"
                        },
                        new
                        {
                            Id = 3,
                            AlertCode = "ALT-03",
                            CreatedAt = new DateTime(2025, 2, 2, 8, 10, 0, 0, DateTimeKind.Unspecified),
                            Message = "Data backup completed successfully",
                            Priority = "Low",
                            Status = "Read",
                            Type = "System"
                        },
                        new
                        {
                            Id = 4,
                            AlertCode = "ALT-10",
                            CreatedAt = new DateTime(2025, 2, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "New patient assigned to Dr John Michael: Olivia Patrick",
                            Priority = "Low",
                            RelatedId = "4569",
                            Status = "Read",
                            Type = "Clinician"
                        },
                        new
                        {
                            Id = 5,
                            AlertCode = "ALT-11",
                            CreatedAt = new DateTime(2025, 2, 10, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            Message = "Workload limit reached for Dr Sarah Peterson",
                            Priority = "High",
                            RelatedId = "698235",
                            Status = "Unread",
                            Type = "Clinician"
                        },
                        new
                        {
                            Id = 6,
                            AlertCode = "ALT-12",
                            CreatedAt = new DateTime(2025, 2, 11, 13, 15, 0, 0, DateTimeKind.Unspecified),
                            Message = "Certification updated for Dr Emily Johnson",
                            Priority = "Medium",
                            RelatedId = "456973",
                            Status = "Read",
                            Type = "Clinician"
                        },
                        new
                        {
                            Id = 7,
                            AlertCode = "ALT-13",
                            CreatedAt = new DateTime(2025, 2, 11, 10, 12, 0, 0, DateTimeKind.Unspecified),
                            Message = "Shift change request approved for Dr David Anderson",
                            Priority = "Low",
                            RelatedId = "325698",
                            Status = "Read",
                            Type = "Clinician"
                        },
                        new
                        {
                            Id = 8,
                            AlertCode = "ALT-14",
                            CreatedAt = new DateTime(2025, 2, 11, 16, 45, 0, 0, DateTimeKind.Unspecified),
                            Message = "Dr Emmanuel State reached maximum patient load",
                            Priority = "High",
                            RelatedId = "258963",
                            Status = "Unread",
                            Type = "Clinician"
                        },
                        new
                        {
                            Id = 9,
                            AlertCode = "ALT-20",
                            CreatedAt = new DateTime(2025, 2, 12, 2, 35, 0, 0, DateTimeKind.Unspecified),
                            Message = "ECG anomaly detected for patient Jacob Flynn – immediate review recommended",
                            Priority = "Critical",
                            RelatedId = "9862",
                            Status = "Unread",
                            Type = "Patient"
                        },
                        new
                        {
                            Id = 10,
                            AlertCode = "ALT-21",
                            CreatedAt = new DateTime(2025, 2, 12, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "Medication conflict detected for patient Alex White (penicillin allergy)",
                            Priority = "High",
                            RelatedId = "4527",
                            Status = "Unread",
                            Type = "Patient"
                        },
                        new
                        {
                            Id = 11,
                            AlertCode = "ALT-22",
                            CreatedAt = new DateTime(2025, 2, 13, 11, 45, 0, 0, DateTimeKind.Unspecified),
                            Message = "Follow-up required for patient Hannah Green – symptoms recorded",
                            Priority = "Medium",
                            RelatedId = "9862",
                            Status = "Unread",
                            Type = "Patient"
                        },
                        new
                        {
                            Id = 12,
                            AlertCode = "ALT-23",
                            CreatedAt = new DateTime(2025, 2, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "Routine blood pressure check due for patient Clara Ashley",
                            Priority = "Low",
                            RelatedId = "6723",
                            Status = "Read",
                            Type = "Patient"
                        },
                        new
                        {
                            Id = 13,
                            AlertCode = "ALT-24",
                            CreatedAt = new DateTime(2025, 2, 14, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Message = "Patient Liam Smith reported recurrent chest discomfort",
                            Priority = "High",
                            RelatedId = "7891",
                            Status = "Unread",
                            Type = "Patient"
                        },
                        new
                        {
                            Id = 14,
                            AlertCode = "ALT-30",
                            CreatedAt = new DateTime(2025, 2, 15, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "11:00 PM Dashboard will be temporarily unavailable due to maintenance",
                            Priority = "Low",
                            Status = "Read",
                            Type = "System"
                        },
                        new
                        {
                            Id = 15,
                            AlertCode = "ALT-31",
                            CreatedAt = new DateTime(2025, 2, 15, 18, 15, 0, 0, DateTimeKind.Unspecified),
                            Message = "Security scan completed — No threats detected",
                            Priority = "Low",
                            Status = "Read",
                            Type = "System"
                        },
                        new
                        {
                            Id = 16,
                            AlertCode = "ALT-32",
                            CreatedAt = new DateTime(2025, 2, 16, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            Message = "New feature rollout: Enhanced reporting tools now available",
                            Priority = "Medium",
                            Status = "Read",
                            Type = "System"
                        },
                        new
                        {
                            Id = 17,
                            AlertCode = "ALT-33",
                            CreatedAt = new DateTime(2025, 2, 16, 14, 45, 0, 0, DateTimeKind.Unspecified),
                            Message = "User activity logs archived successfully",
                            Priority = "Low",
                            Status = "Read",
                            Type = "System"
                        },
                        new
                        {
                            Id = 18,
                            AlertCode = "ALT-34",
                            CreatedAt = new DateTime(2025, 2, 17, 3, 20, 0, 0, DateTimeKind.Unspecified),
                            Message = "Critical vulnerability patch applied to server infrastructure",
                            Priority = "Critical",
                            Status = "Unread",
                            Type = "System"
                        },
                        new
                        {
                            Id = 19,
                            AlertCode = "ALT-35",
                            CreatedAt = new DateTime(2025, 2, 17, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "Monthly system performance report is now available",
                            Priority = "Medium",
                            Status = "Read",
                            Type = "System"
                        });
                });

            modelBuilder.Entity("GrapheneTrace_GP.Areas.Admin.Models.ClinicianAlert", b =>
                {
                    b.Property<int>("AlertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlertId"));

                    b.Property<DateTime>("AlertDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClinicianId")
                        .HasColumnType("int");

                    b.HasKey("AlertId");

                    b.HasIndex("ClinicianId");

                    b.ToTable("ClinicianAlerts");

                    b.HasData(
                        new
                        {
                            AlertId = 1,
                            AlertDateTime = new DateTime(2025, 2, 11, 13, 15, 0, 0, DateTimeKind.Unspecified),
                            AlertType = "Certification updated",
                            ClinicianId = 1
                        },
                        new
                        {
                            AlertId = 2,
                            AlertDateTime = new DateTime(2025, 2, 11, 10, 12, 0, 0, DateTimeKind.Unspecified),
                            AlertType = "Profile updated",
                            ClinicianId = 1
                        },
                        new
                        {
                            AlertId = 3,
                            AlertDateTime = new DateTime(2025, 2, 11, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            AlertType = "New patient assigned",
                            ClinicianId = 1
                        },
                        new
                        {
                            AlertId = 4,
                            AlertDateTime = new DateTime(2025, 2, 11, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            AlertType = "Status active",
                            ClinicianId = 2
                        },
                        new
                        {
                            AlertId = 5,
                            AlertDateTime = new DateTime(2025, 2, 11, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            AlertType = "Status inactive",
                            ClinicianId = 2
                        },
                        new
                        {
                            AlertId = 6,
                            AlertDateTime = new DateTime(2025, 2, 10, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            AlertType = "High workload",
                            ClinicianId = 2
                        },
                        new
                        {
                            AlertId = 7,
                            AlertDateTime = new DateTime(2025, 2, 11, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            AlertType = "Certification expired",
                            ClinicianId = 2
                        },
                        new
                        {
                            AlertId = 8,
                            AlertDateTime = new DateTime(2025, 2, 9, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            AlertType = "Shift change request",
                            ClinicianId = 3
                        },
                        new
                        {
                            AlertId = 9,
                            AlertDateTime = new DateTime(2025, 2, 9, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            AlertType = "Status active",
                            ClinicianId = 3
                        },
                        new
                        {
                            AlertId = 10,
                            AlertDateTime = new DateTime(2025, 2, 8, 17, 40, 0, 0, DateTimeKind.Unspecified),
                            AlertType = "Documents uploaded",
                            ClinicianId = 4
                        },
                        new
                        {
                            AlertId = 11,
                            AlertDateTime = new DateTime(2025, 2, 8, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            AlertType = "Verification pending",
                            ClinicianId = 4
                        },
                        new
                        {
                            AlertId = 12,
                            AlertDateTime = new DateTime(2025, 2, 7, 14, 25, 0, 0, DateTimeKind.Unspecified),
                            AlertType = "New patient assigned",
                            ClinicianId = 5
                        },
                        new
                        {
                            AlertId = 13,
                            AlertDateTime = new DateTime(2025, 2, 7, 9, 50, 0, 0, DateTimeKind.Unspecified),
                            AlertType = "Status inactive",
                            ClinicianId = 5
                        },
                        new
                        {
                            AlertId = 14,
                            AlertDateTime = new DateTime(2025, 2, 6, 11, 10, 0, 0, DateTimeKind.Unspecified),
                            AlertType = "Shift schedule updated",
                            ClinicianId = 6
                        },
                        new
                        {
                            AlertId = 15,
                            AlertDateTime = new DateTime(2025, 2, 5, 16, 45, 0, 0, DateTimeKind.Unspecified),
                            AlertType = "High workload",
                            ClinicianId = 7
                        },
                        new
                        {
                            AlertId = 16,
                            AlertDateTime = new DateTime(2025, 2, 4, 10, 20, 0, 0, DateTimeKind.Unspecified),
                            AlertType = "Profile updated",
                            ClinicianId = 7
                        },
                        new
                        {
                            AlertId = 17,
                            AlertDateTime = new DateTime(2025, 2, 3, 14, 20, 0, 0, DateTimeKind.Unspecified),
                            AlertType = "New patient assigned",
                            ClinicianId = 8
                        },
                        new
                        {
                            AlertId = 18,
                            AlertDateTime = new DateTime(2025, 2, 3, 8, 40, 0, 0, DateTimeKind.Unspecified),
                            AlertType = "Certification updated",
                            ClinicianId = 8
                        },
                        new
                        {
                            AlertId = 19,
                            AlertDateTime = new DateTime(2025, 2, 2, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            AlertType = "Emergency override assigned",
                            ClinicianId = 9
                        },
                        new
                        {
                            AlertId = 20,
                            AlertDateTime = new DateTime(2025, 2, 1, 9, 10, 0, 0, DateTimeKind.Unspecified),
                            AlertType = "New patient assigned",
                            ClinicianId = 10
                        },
                        new
                        {
                            AlertId = 21,
                            AlertDateTime = new DateTime(2025, 1, 29, 15, 35, 0, 0, DateTimeKind.Unspecified),
                            AlertType = "Certification expired",
                            ClinicianId = 11
                        },
                        new
                        {
                            AlertId = 22,
                            AlertDateTime = new DateTime(2025, 1, 29, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            AlertType = "Shift change request",
                            ClinicianId = 11
                        });
                });

            modelBuilder.Entity("GrapheneTrace_GP.Areas.Admin.Models.ClinicianAssignments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedPatients")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssignedWardUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClinicianId")
                        .HasColumnType("int");

                    b.Property<int>("CurrentAppointments")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastAssignmentUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Supervisor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClinicianId")
                        .IsUnique();

                    b.ToTable("ClinicianAssignments");
                });

            modelBuilder.Entity("GrapheneTrace_GP.Areas.Admin.Models.ClinicianProfessionalInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClinicianId")
                        .HasColumnType("int");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenceNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Qualifications")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoomAssigned")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Speciality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkSchedule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClinicianId")
                        .IsUnique();

                    b.ToTable("ClinicianProfessionalInfos");
                });

            modelBuilder.Entity("GrapheneTrace_GP.Areas.Admin.Models.Clinicians", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssignedWardUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClinicianAge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClinicianFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClinicianId")
                        .HasColumnType("int");

                    b.Property<string>("ClinicianLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClinicianSpeciality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Supervisor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Clinicians");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "1 Main Street",
                            City = "London",
                            ClinicianAge = "40",
                            ClinicianFirstName = "John",
                            ClinicianId = 852693,
                            ClinicianLastName = "Michael",
                            ClinicianSpeciality = "Cardiologist",
                            CreatedAt = new DateTime(2025, 12, 14, 12, 1, 30, 421, DateTimeKind.Utc).AddTicks(1139),
                            DateOfBirth = new DateTime(1984, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john.michael@example.com",
                            Gender = "Male",
                            Phone = "07111111111",
                            PostCode = "A1 1AA",
                            Status = "Active",
                            Title = "Dr.",
                            UpdatedAt = new DateTime(2025, 12, 14, 12, 1, 30, 421, DateTimeKind.Utc).AddTicks(1143)
                        },
                        new
                        {
                            Id = 2,
                            Address = "2 Main Street",
                            City = "London",
                            ClinicianAge = "32",
                            ClinicianFirstName = "Sarah",
                            ClinicianId = 698235,
                            ClinicianLastName = "Peterson",
                            ClinicianSpeciality = "Neurology",
                            CreatedAt = new DateTime(2025, 12, 14, 12, 1, 30, 421, DateTimeKind.Utc).AddTicks(1297),
                            DateOfBirth = new DateTime(1992, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sarah.peterson@hospital.com",
                            Gender = "Female",
                            Phone = "07222222222",
                            PostCode = "A2 2BB",
                            Status = "Active",
                            Title = "Dr.",
                            UpdatedAt = new DateTime(2025, 12, 14, 12, 1, 30, 421, DateTimeKind.Utc).AddTicks(1297)
                        },
                        new
                        {
                            Id = 3,
                            Address = "3 Main Street",
                            City = "London",
                            ClinicianAge = "30",
                            ClinicianFirstName = "Emily",
                            ClinicianId = 456973,
                            ClinicianLastName = "Johnson",
                            ClinicianSpeciality = "Pediatrics",
                            CreatedAt = new DateTime(2025, 12, 14, 12, 1, 30, 421, DateTimeKind.Utc).AddTicks(1306),
                            DateOfBirth = new DateTime(1994, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emily.johnson@hospital.com",
                            Gender = "Female",
                            Phone = "07333333333",
                            PostCode = "A3 3CC",
                            Status = "Active",
                            Title = "Dr.",
                            UpdatedAt = new DateTime(2025, 12, 14, 12, 1, 30, 421, DateTimeKind.Utc).AddTicks(1307)
                        },
                        new
                        {
                            Id = 4,
                            Address = "4 Main Street",
                            City = "London",
                            ClinicianAge = "29",
                            ClinicianFirstName = "David",
                            ClinicianId = 325698,
                            ClinicianLastName = "Anderson",
                            ClinicianSpeciality = "Neurologist",
                            CreatedAt = new DateTime(2025, 12, 14, 12, 1, 30, 421, DateTimeKind.Utc).AddTicks(1314),
                            DateOfBirth = new DateTime(1995, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "david.anderson@hospital.com",
                            Gender = "Male",
                            Phone = "07444444444",
                            PostCode = "A4 4DD",
                            Status = "Active",
                            Title = "Dr.",
                            UpdatedAt = new DateTime(2025, 12, 14, 12, 1, 30, 421, DateTimeKind.Utc).AddTicks(1314)
                        },
                        new
                        {
                            Id = 5,
                            Address = "5 Main Street",
                            City = "London",
                            ClinicianAge = "49",
                            ClinicianFirstName = "Emmanuel",
                            ClinicianId = 258963,
                            ClinicianLastName = "State",
                            ClinicianSpeciality = "Surgeon",
                            CreatedAt = new DateTime(2025, 12, 14, 12, 1, 30, 421, DateTimeKind.Utc).AddTicks(1320),
                            DateOfBirth = new DateTime(1975, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emmanuel.state@hospital.com",
                            Gender = "Male",
                            Phone = "07555555555",
                            PostCode = "A5 5EE",
                            Status = "Active",
                            Title = "Dr.",
                            UpdatedAt = new DateTime(2025, 12, 14, 12, 1, 30, 421, DateTimeKind.Utc).AddTicks(1321)
                        },
                        new
                        {
                            Id = 6,
                            Address = "6 Main Street",
                            City = "London",
                            ClinicianAge = "42",
                            ClinicianFirstName = "Mike",
                            ClinicianId = 258694,
                            ClinicianLastName = "Stephen",
                            ClinicianSpeciality = "Radiologist",
                            CreatedAt = new DateTime(2025, 12, 14, 12, 1, 30, 421, DateTimeKind.Utc).AddTicks(1326),
                            DateOfBirth = new DateTime(1982, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mike.stephen@hospital.com",
                            Gender = "Male",
                            Phone = "07666666666",
                            PostCode = "A6 6FF",
                            Status = "Active",
                            Title = "Dr.",
                            UpdatedAt = new DateTime(2025, 12, 14, 12, 1, 30, 421, DateTimeKind.Utc).AddTicks(1327)
                        },
                        new
                        {
                            Id = 7,
                            Address = "7 Main Street",
                            City = "London",
                            ClinicianAge = "38",
                            ClinicianFirstName = "Noah",
                            ClinicianId = 784561,
                            ClinicianLastName = "Hyper",
                            ClinicianSpeciality = "Psychiatrist",
                            CreatedAt = new DateTime(2025, 12, 14, 12, 1, 30, 421, DateTimeKind.Utc).AddTicks(1332),
                            DateOfBirth = new DateTime(1986, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "noah.hyper@hospital.com",
                            Gender = "Male",
                            Phone = "07777777777",
                            PostCode = "A7 7GG",
                            Status = "Active",
                            Title = "Dr.",
                            UpdatedAt = new DateTime(2025, 12, 14, 12, 1, 30, 421, DateTimeKind.Utc).AddTicks(1333)
                        },
                        new
                        {
                            Id = 8,
                            Address = "8 Main Street",
                            City = "London",
                            ClinicianAge = "38",
                            ClinicianFirstName = "Helen",
                            ClinicianId = 125489,
                            ClinicianLastName = "Cooke",
                            ClinicianSpeciality = "Gynaecologist",
                            CreatedAt = new DateTime(2025, 12, 14, 12, 1, 30, 421, DateTimeKind.Utc).AddTicks(1338),
                            DateOfBirth = new DateTime(1986, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "helen.cooke@hospital.com",
                            Gender = "Female",
                            Phone = "07888888888",
                            PostCode = "A8 8HH",
                            Status = "Active",
                            Title = "Dr.",
                            UpdatedAt = new DateTime(2025, 12, 14, 12, 1, 30, 421, DateTimeKind.Utc).AddTicks(1339)
                        },
                        new
                        {
                            Id = 9,
                            Address = "9 Main Street",
                            City = "London",
                            ClinicianAge = "42",
                            ClinicianFirstName = "Rose",
                            ClinicianId = 508342,
                            ClinicianLastName = "Night",
                            ClinicianSpeciality = "Surgeon",
                            CreatedAt = new DateTime(2025, 12, 14, 12, 1, 30, 421, DateTimeKind.Utc).AddTicks(1343),
                            DateOfBirth = new DateTime(1982, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "rose.night@hospital.com",
                            Gender = "Female",
                            Phone = "07999999999",
                            PostCode = "A9 9JJ",
                            Status = "Active",
                            Title = "Dr.",
                            UpdatedAt = new DateTime(2025, 12, 14, 12, 1, 30, 421, DateTimeKind.Utc).AddTicks(1344)
                        },
                        new
                        {
                            Id = 10,
                            Address = "10 Main Street",
                            City = "London",
                            ClinicianAge = "54",
                            ClinicianFirstName = "Jake",
                            ClinicianId = 159753,
                            ClinicianLastName = "Watson",
                            ClinicianSpeciality = "Orthopaedic",
                            CreatedAt = new DateTime(2025, 12, 14, 12, 1, 30, 421, DateTimeKind.Utc).AddTicks(1349),
                            DateOfBirth = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jake.watson@hospital.com",
                            Gender = "Male",
                            Phone = "07010101010",
                            PostCode = "B1 1AA",
                            Status = "Active",
                            Title = "Dr.",
                            UpdatedAt = new DateTime(2025, 12, 14, 12, 1, 30, 421, DateTimeKind.Utc).AddTicks(1350)
                        },
                        new
                        {
                            Id = 11,
                            Address = "11 Main Street",
                            City = "London",
                            ClinicianAge = "34",
                            ClinicianFirstName = "Emma",
                            ClinicianId = 753561,
                            ClinicianLastName = "Richard",
                            ClinicianSpeciality = "Dermatologist",
                            CreatedAt = new DateTime(2025, 12, 14, 12, 1, 30, 421, DateTimeKind.Utc).AddTicks(1356),
                            DateOfBirth = new DateTime(1990, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emma.richard@hospital.com",
                            Gender = "Female",
                            Phone = "07020202020",
                            PostCode = "B2 2BB",
                            Status = "Active",
                            Title = "Dr.",
                            UpdatedAt = new DateTime(2025, 12, 14, 12, 1, 30, 421, DateTimeKind.Utc).AddTicks(1356)
                        });
                });

            modelBuilder.Entity("GrapheneTrace_GP.Areas.Admin.Models.CliniciansProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClinicianAge")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClinicianFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClinicianLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CliniciansProfiles");
                });

            modelBuilder.Entity("GrapheneTrace_GP.Areas.Admin.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Allergies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BloodGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChronicConditions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ClinicianId")
                        .HasColumnType("int");

                    b.Property<string>("CurrentMedication")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateReviewed")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyContactNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Height")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastMedicalCheckup")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NHSNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PastSurgeries")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientAge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Purpose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Relationship")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Smoking")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VaccinationStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerificationStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weight")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PatientId");

                    b.HasIndex("ClinicianId");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            PatientId = 2693,
                            Address = "10 Downing Street",
                            City = "London",
                            ClinicianId = 2,
                            DateOfBirth = new DateTime(1984, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sophie.night@gmail.com",
                            FirstName = "Sophie",
                            Gender = "Female",
                            LastName = "Night",
                            PatientAge = "40",
                            Phone = "07012345678",
                            PostCode = "SW1A 2AA",
                            Status = "Active",
                            Title = "Mrs."
                        },
                        new
                        {
                            PatientId = 5987,
                            Address = "20 Baker Street",
                            City = "London",
                            ClinicianId = 4,
                            DateOfBirth = new DateTime(1992, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "janee.harrison@gmail.com",
                            FirstName = "Janee",
                            Gender = "Female",
                            LastName = "Harrison",
                            PatientAge = "32",
                            Phone = "07087654321",
                            PostCode = "NW1 6XE",
                            Status = "Active",
                            Title = "Ms."
                        },
                        new
                        {
                            PatientId = 8963,
                            Address = "30 Oxford Street",
                            City = "London",
                            ClinicianId = 1,
                            DateOfBirth = new DateTime(1995, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mike.jackson@gmail.com",
                            FirstName = "Mike",
                            Gender = "Male",
                            LastName = "Jackson",
                            PatientAge = "29",
                            Phone = "07011223344",
                            PostCode = "W1D 1BS",
                            Status = "Alert",
                            Title = "Mr"
                        },
                        new
                        {
                            PatientId = 1257,
                            Address = "40 King Street",
                            City = "London",
                            ClinicianId = 5,
                            DateOfBirth = new DateTime(1978, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "peter.benjamin@gmail.com",
                            FirstName = "Peter",
                            Gender = "Male",
                            LastName = "Benjamin",
                            PatientAge = "49",
                            Phone = "07098765432",
                            PostCode = "W1F 0UT",
                            Status = "Active",
                            Title = "Mr."
                        },
                        new
                        {
                            PatientId = 9862,
                            Address = "50 Queen Street",
                            City = "London",
                            ClinicianId = 1,
                            DateOfBirth = new DateTime(1988, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Hannah.green@gmail.com",
                            FirstName = "Hannah",
                            Gender = "Female",
                            LastName = "Green",
                            PatientAge = "42",
                            Phone = "07012345678",
                            PostCode = "W1A 1AA",
                            Status = "Active",
                            Title = "Mrs."
                        },
                        new
                        {
                            PatientId = 3654,
                            Address = "60 King Street",
                            City = "London",
                            ClinicianId = 5,
                            DateOfBirth = new DateTime(1986, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "andy.bryan@gmail.com",
                            FirstName = "Andy",
                            Gender = "Male",
                            LastName = "Bryan",
                            PatientAge = "38",
                            Phone = "07012345678",
                            PostCode = "W1F 0UT",
                            Status = "Not Active",
                            Title = "Mr"
                        },
                        new
                        {
                            PatientId = 4527,
                            Address = "70 King Street",
                            City = "London",
                            ClinicianId = 4,
                            DateOfBirth = new DateTime(1986, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "alex.white@gmail.com",
                            FirstName = "Alex",
                            Gender = "Male",
                            LastName = "White",
                            PatientAge = "38",
                            Phone = "07012345678",
                            PostCode = "W1F 0UT",
                            Status = "Active",
                            Title = "Mr"
                        },
                        new
                        {
                            PatientId = 6723,
                            Address = "80 Queen Street",
                            City = "London",
                            ClinicianId = 2,
                            DateOfBirth = new DateTime(1994, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "clara.ashley@gmail.com",
                            FirstName = "Clara",
                            Gender = "Female",
                            LastName = "Ashley",
                            PatientAge = "30",
                            Phone = "07012345678",
                            PostCode = "W1A 1AA",
                            Status = "Not Active",
                            Title = "Mrs."
                        },
                        new
                        {
                            PatientId = 7894,
                            Address = "90 Queen Street",
                            City = "London",
                            ClinicianId = 7,
                            DateOfBirth = new DateTime(1990, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "diana.prince@gmail.com",
                            FirstName = "Diana",
                            Gender = "Female",
                            LastName = "Prince",
                            PatientAge = "34",
                            Phone = "07012345678",
                            PostCode = "W1A 1AA",
                            Status = "Not Active",
                            Title = "Ms."
                        },
                        new
                        {
                            PatientId = 3456,
                            Address = "100 Gotham Street",
                            City = "Gotham",
                            ClinicianId = 8,
                            DateOfBirth = new DateTime(1978, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "richard.watson@gmail.com",
                            FirstName = "Richard",
                            Gender = "Male",
                            LastName = "Watson",
                            PatientAge = "45",
                            Phone = "07012345678",
                            PostCode = "G1TH 0TH",
                            Status = "Active",
                            Title = "Mr"
                        },
                        new
                        {
                            PatientId = 9123,
                            Address = "110 Gotham Street",
                            City = "Gotham",
                            ClinicianId = 8,
                            DateOfBirth = new DateTime(1995, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "james.brown@gmail.com",
                            FirstName = "James",
                            Gender = "Female",
                            LastName = "Brown",
                            PatientAge = "28",
                            Phone = "07012345678",
                            PostCode = "G1TH 0TH",
                            Status = "Not Active",
                            Title = "Mr."
                        },
                        new
                        {
                            PatientId = 4569,
                            Address = "20 Avenue Glass Rd",
                            City = "Bristol",
                            ClinicianId = 1,
                            DateOfBirth = new DateTime(1986, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Olivia12.Patrick@gmail.com",
                            FirstName = "Olivia",
                            Gender = "Female",
                            LastName = "Patrick",
                            PatientAge = "39",
                            Phone = "07452136925",
                            PostCode = "B17G BYR",
                            Status = "Active",
                            Title = "Ms"
                        },
                        new
                        {
                            PatientId = 7891,
                            Address = "30 River Side",
                            City = "Manchester",
                            ClinicianId = 3,
                            DateOfBirth = new DateTime(1988, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "liam.smith@gmail.com",
                            FirstName = "Liam",
                            Gender = "Male",
                            LastName = "Smith",
                            PatientAge = "35",
                            Phone = "07345678912",
                            PostCode = "M1 2AB",
                            Status = "Active",
                            Title = "Mr."
                        },
                        new
                        {
                            PatientId = 2345,
                            Address = "40 River Side",
                            City = "Manchester",
                            ClinicianId = 6,
                            DateOfBirth = new DateTime(1982, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ava.johnson@gmail.com",
                            FirstName = "Ava",
                            Gender = "Female",
                            LastName = "Johnson",
                            PatientAge = "41",
                            Phone = "07345678912",
                            PostCode = "M1 2AB",
                            Status = "Not Active",
                            Title = "Mrs."
                        },
                        new
                        {
                            PatientId = 6789,
                            Address = "50 River Side",
                            City = "Manchester",
                            ClinicianId = 7,
                            DateOfBirth = new DateTime(1994, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "isabella.williams@gmail.com",
                            FirstName = "Isabella",
                            Gender = "Female",
                            LastName = "Williams",
                            PatientAge = "29",
                            Phone = "07412345678",
                            PostCode = "M1 2AB",
                            Status = "Active",
                            Title = "Ms."
                        },
                        new
                        {
                            PatientId = 3457,
                            Address = "60 River Side",
                            City = "Manchester",
                            ClinicianId = 6,
                            DateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "noah.brown@gmail.com",
                            FirstName = "Noah",
                            Gender = "Male",
                            LastName = "Brown",
                            PatientAge = "33",
                            Phone = "07512345678",
                            PostCode = "M1 2AB",
                            Status = "Active",
                            Title = "Mr."
                        },
                        new
                        {
                            PatientId = 8123,
                            Address = "12 Wood Street",
                            City = "London",
                            ClinicianId = 2,
                            DateOfBirth = new DateTime(1987, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "harvey.cole@gmail.com",
                            FirstName = "Harvey",
                            Gender = "Male",
                            LastName = "Cole",
                            PatientAge = "37",
                            Phone = "07581234567",
                            PostCode = "E2 4AA",
                            Status = "Active",
                            Title = "Mr."
                        },
                        new
                        {
                            PatientId = 8125,
                            Address = "28 Crescent Lane",
                            City = "Manchester",
                            ClinicianId = 3,
                            DateOfBirth = new DateTime(1980, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "layla.stevens@gmail.com",
                            FirstName = "Layla",
                            Gender = "Female",
                            LastName = "Stevens",
                            PatientAge = "44",
                            Phone = "07411122233",
                            PostCode = "M3 4GH",
                            Status = "Active",
                            Title = "Ms."
                        },
                        new
                        {
                            PatientId = 8126,
                            Address = "4 Mill View",
                            City = "Manchester",
                            ClinicianId = 3,
                            DateOfBirth = new DateTime(1972, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "brandon.lee@gmail.com",
                            FirstName = "Brandon",
                            Gender = "Male",
                            LastName = "Lee",
                            PatientAge = "52",
                            Phone = "07422233344",
                            PostCode = "M4 1AB",
                            Status = "Not Active",
                            Title = "Mr."
                        },
                        new
                        {
                            PatientId = 8127,
                            Address = "7 Elm Park",
                            City = "London",
                            ClinicianId = 4,
                            DateOfBirth = new DateTime(1998, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tom.barker@gmail.com",
                            FirstName = "Tom",
                            Gender = "Male",
                            LastName = "Barker",
                            PatientAge = "26",
                            Phone = "07399988877",
                            PostCode = "SW1 7DF",
                            Status = "Active",
                            Title = "Mr."
                        },
                        new
                        {
                            PatientId = 8128,
                            Address = "22 Green Lane",
                            City = "London",
                            ClinicianId = 4,
                            DateOfBirth = new DateTime(1976, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nora.hughes@gmail.com",
                            FirstName = "Nora",
                            Gender = "Female",
                            LastName = "Hughes",
                            PatientAge = "48",
                            Phone = "07311155522",
                            PostCode = "SW1 9GH",
                            Status = "Active",
                            Title = "Mrs."
                        },
                        new
                        {
                            PatientId = 8129,
                            Address = "18 Maple Street",
                            City = "Bristol",
                            ClinicianId = 1,
                            DateOfBirth = new DateTime(1993, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ethan.morris@gmail.com",
                            FirstName = "Ethan",
                            Gender = "Male",
                            LastName = "Morris",
                            PatientAge = "31",
                            Phone = "07812345670",
                            PostCode = "BS1 3DA",
                            Status = "Active",
                            Title = "Mr."
                        },
                        new
                        {
                            PatientId = 8130,
                            Address = "45 River Way",
                            City = "Bristol",
                            ClinicianId = 1,
                            DateOfBirth = new DateTime(1988, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "chloe.adams@gmail.com",
                            FirstName = "Chloe",
                            Gender = "Female",
                            LastName = "Adams",
                            PatientAge = "36",
                            Phone = "07898732100",
                            PostCode = "BS2 5HB",
                            Status = "Not Active",
                            Title = "Ms."
                        },
                        new
                        {
                            PatientId = 8131,
                            Address = "33 Oak Road",
                            City = "London",
                            ClinicianId = 5,
                            DateOfBirth = new DateTime(1984, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "kyle.garcia@gmail.com",
                            FirstName = "Kyle",
                            Gender = "Male",
                            LastName = "Garcia",
                            PatientAge = "40",
                            Phone = "07788822211",
                            PostCode = "NW1 5RT",
                            Status = "Active",
                            Title = "Mr."
                        },
                        new
                        {
                            PatientId = 8132,
                            Address = "91 Hill Street",
                            City = "London",
                            ClinicianId = 5,
                            DateOfBirth = new DateTime(2000, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "amelia.scott@gmail.com",
                            FirstName = "Amelia",
                            Gender = "Female",
                            LastName = "Scott",
                            PatientAge = "24",
                            Phone = "07722288899",
                            PostCode = "NW3 8YZ",
                            Status = "Active",
                            Title = "Ms."
                        },
                        new
                        {
                            PatientId = 8133,
                            Address = "4 Silver Street",
                            City = "Manchester",
                            ClinicianId = 6,
                            DateOfBirth = new DateTime(1991, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jacob.shaw@gmail.com",
                            FirstName = "Jacob",
                            Gender = "Male",
                            LastName = "Shaw",
                            PatientAge = "33",
                            Phone = "07655533322",
                            PostCode = "M2 7EG",
                            Status = "Active",
                            Title = "Mr."
                        },
                        new
                        {
                            PatientId = 8134,
                            Address = "20 Brook Lane",
                            City = "Manchester",
                            ClinicianId = 6,
                            DateOfBirth = new DateTime(1978, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "grace.miller@gmail.com",
                            FirstName = "Grace",
                            Gender = "Female",
                            LastName = "Miller",
                            PatientAge = "46",
                            Phone = "07611122244",
                            PostCode = "M2 9GT",
                            Status = "Active",
                            Title = "Mrs."
                        },
                        new
                        {
                            PatientId = 8135,
                            Address = "14 Sunset Drive",
                            City = "Liverpool",
                            ClinicianId = 7,
                            DateOfBirth = new DateTime(1985, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ryan.evans@gmail.com",
                            FirstName = "Ryan",
                            Gender = "Male",
                            LastName = "Evans",
                            PatientAge = "39",
                            Phone = "07544455566",
                            PostCode = "L1 2AA",
                            Status = "Not Active",
                            Title = "Mr."
                        },
                        new
                        {
                            PatientId = 8136,
                            Address = "22 Hilltop Road",
                            City = "Liverpool",
                            ClinicianId = 7,
                            DateOfBirth = new DateTime(1997, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sophia.clarke@gmail.com",
                            FirstName = "Sophia",
                            Gender = "Female",
                            LastName = "Clarke",
                            PatientAge = "27",
                            Phone = "07555566677",
                            PostCode = "L2 1BB",
                            Status = "Active",
                            Title = "Ms."
                        },
                        new
                        {
                            PatientId = 8137,
                            Address = "10 Riverbank",
                            City = "Gotham",
                            ClinicianId = 8,
                            DateOfBirth = new DateTime(1974, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ella.turner@gmail.com",
                            FirstName = "Ella",
                            Gender = "Female",
                            LastName = "Turner",
                            PatientAge = "50",
                            Phone = "07477788822",
                            PostCode = "G1TH 2TT",
                            Status = "Active",
                            Title = "Mrs."
                        },
                        new
                        {
                            PatientId = 8138,
                            Address = "18 Lantern Lane",
                            City = "Gotham",
                            ClinicianId = 8,
                            DateOfBirth = new DateTime(1983, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nathan.brooks@gmail.com",
                            FirstName = "Nathan",
                            Gender = "Male",
                            LastName = "Brooks",
                            PatientAge = "41",
                            Phone = "07422244455",
                            PostCode = "G1TH 3PP",
                            Status = "Active",
                            Title = "Mr."
                        },
                        new
                        {
                            PatientId = 8139,
                            Address = "6 Forest Road",
                            City = "London",
                            ClinicianId = 2,
                            DateOfBirth = new DateTime(1990, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "leo.robinson@gmail.com",
                            FirstName = "Leo",
                            Gender = "Male",
                            LastName = "Robinson",
                            PatientAge = "34",
                            Phone = "07522113344",
                            PostCode = "E1 7HH",
                            Status = "Active",
                            Title = "Mr."
                        },
                        new
                        {
                            PatientId = 8140,
                            Address = "8 Oakwood",
                            City = "London",
                            ClinicianId = 5,
                            DateOfBirth = new DateTime(1993, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "holly.grant@gmail.com",
                            FirstName = "Holly",
                            Gender = "Female",
                            LastName = "Grant",
                            PatientAge = "31",
                            Phone = "07512398765",
                            PostCode = "NW8 1GG",
                            Status = "Not Active",
                            Title = "Ms."
                        },
                        new
                        {
                            PatientId = 8141,
                            Address = "39 Slope View",
                            City = "Manchester",
                            ClinicianId = 3,
                            DateOfBirth = new DateTime(1977, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "aaron.foster@gmail.com",
                            FirstName = "Aaron",
                            Gender = "Male",
                            LastName = "Foster",
                            PatientAge = "47",
                            Phone = "07489012345",
                            PostCode = "M4 9QA",
                            Status = "Active",
                            Title = "Mr."
                        });
                });

            modelBuilder.Entity("Appointment", b =>
                {
                    b.HasOne("GrapheneTrace_GP.Areas.Admin.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("GrapheneTrace_GP.Areas.Admin.Models.ClinicianAlert", b =>
                {
                    b.HasOne("GrapheneTrace_GP.Areas.Admin.Models.Clinicians", "Clinician")
                        .WithMany("Alerts")
                        .HasForeignKey("ClinicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinician");
                });

            modelBuilder.Entity("GrapheneTrace_GP.Areas.Admin.Models.ClinicianAssignments", b =>
                {
                    b.HasOne("GrapheneTrace_GP.Areas.Admin.Models.CliniciansProfile", "Clinician")
                        .WithOne("Assignments")
                        .HasForeignKey("GrapheneTrace_GP.Areas.Admin.Models.ClinicianAssignments", "ClinicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinician");
                });

            modelBuilder.Entity("GrapheneTrace_GP.Areas.Admin.Models.ClinicianProfessionalInfo", b =>
                {
                    b.HasOne("GrapheneTrace_GP.Areas.Admin.Models.CliniciansProfile", "Clinician")
                        .WithOne("ProfessionalInfos")
                        .HasForeignKey("GrapheneTrace_GP.Areas.Admin.Models.ClinicianProfessionalInfo", "ClinicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinician");
                });

            modelBuilder.Entity("GrapheneTrace_GP.Areas.Admin.Models.Patient", b =>
                {
                    b.HasOne("GrapheneTrace_GP.Areas.Admin.Models.Clinicians", "Clinician")
                        .WithMany("Patients")
                        .HasForeignKey("ClinicianId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Clinician");
                });

            modelBuilder.Entity("GrapheneTrace_GP.Areas.Admin.Models.Clinicians", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Patients");
                });

            modelBuilder.Entity("GrapheneTrace_GP.Areas.Admin.Models.CliniciansProfile", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("ProfessionalInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
